name: Update Trace

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * 1'

jobs:
  trace-update:
    name: Update Trace
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa ${{ secrets.HOST }} >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
          cat >>~/.ssh/config <<END
          Host geth
            HostName ${{ secrets.HOST }}
            User ${{ secrets.USER }}
            IdentityFile ~/.ssh/id_rsa
            StrictHostKeyChecking no
          END
      - name: Dump latest trace
        id: dump
        run: |
          blk=$(ssh geth "curl -s -X POST -H \"Content-Type: application/json\" --data '{\"jsonrpc\":\"2.0\",\"method\":\"eth_blockNumber\", \"params\":[], \"id\": 99}' 127.0.0.1:8545 | jq -r .result")
          ssh geth "curl -s -X POST -H \"Content-Type: application/json\" --data '{\"jsonrpc\":\"2.0\",\"method\":\"scroll_getBlockTraceByNumberOrHash\", \"params\":[\"'$blk'\"], \"id\": 99}' 127.0.0.1:8545" > mainnet_blocks/${blk}.json
          echo "block_number=$blk" > $GITHUB_OUTPUT
      - name: Commit
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -am "update trace"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6.1.0
        with:
          labels: chore
          branch: chore/update-trace
          base: master
          title: '[chore] update trace'
          body: add block ${{ steps.dump.outputs.block_number }} trace